# Generated by Django 5.2.3 on 2025-07-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='threshold',
            new_name='temperature_threshold',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='humidity_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='pressure_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='wind_speed_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
