# Generated by Django 5.2.3 on 2025-07-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_threshold_usersubscription_temperature_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='temperature_alert_direction',
            field=models.CharField(choices=[('above', 'Выше порога'), ('below', 'Ниже порога')], default='above', max_length=5),
        ),
    ]
