# Generated by Django 5.2.3 on 2025-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription_temperature_alert_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
