# Generated by Django 5.2.3 on 2025-07-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['user', 'city']},
        ),
    ]
