# Generated by Django 5.2.3 on 2025-07-24 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_city_latitude_remove_city_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name', 'country']},
        ),
        migrations.AlterModelOptions(
            name='weatherhistory',
            options={'get_latest_by': 'updated_at', 'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='weatherhistory',
            unique_together={('user', 'city', 'updated_at')},
        ),
        migrations.AddIndex(
            model_name='weatherhistory',
            index=models.Index(fields=['city'], name='weather_wea_city_id_1afc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherhistory',
            index=models.Index(fields=['user'], name='weather_wea_user_id_2821b7_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherhistory',
            index=models.Index(fields=['-updated_at'], name='weather_wea_updated_01e9f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatherhistory',
            constraint=models.UniqueConstraint(fields=('user', 'city', 'updated_at'), name='unique_user_city_time'),
        ),
    ]
